[package]
name = "wbroker-rs"
version = "0.2.0"
edition = "2021"

[dependencies]
rppal = { version = "0.22.1", features = [] }
chrono = "0.4.39"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
strip = "symbols"
